export class StudentDetails{
  constructor(
  public studentId ="",
	public fname ="",
	public mName ="",
	public lname ="",
	public title ="",
	public birthDate ="",
	public gender ="",
	public maritalStatus ="",
	public children ="",	
	public nation  ="",
	public district  ="",
	public county ="",
	public subCounty ="",
	public parish ="",
	public village ="",
	public phoneAddress1 ="",
	public phoneAddress2 ="",
	public emailAddress ="",
  public keenName ="",
	public keenRelationship ="",
	public keenPhone ="",
	public keenEmail ="",
	public keenAddress ="",
	public educationLevel ="",
	public specify ="",
	public institutions ="",
	public IntakeDate ="",
	public branchNum ="",
	public studyprogramme ="",
	public EntryLevel ="",
	public courseCode ="",
	public studentStatus  ="",
	public passwords ="" ,
	public adminId =""
  ){}
}